### ISSUE TITLE
The site is broken

### ISSUE THREAD

**Issue by sm4rk0** [Diederikjh/fortunefortoday#1]
Your site  [http://fortunefortoday.com/](http://fortunefortoday.com/) redirects to [https://zeus.nexus.co.za:8443/login.php3](https://zeus.nexus.co.za:8443/login.php3).
I know this github project is not intended for such an issue, but this was the easiest way for me to report it.

**Comment by Diederikjh** [comment]
Hi Marko,
Thanks for reporting this. I'll look into this, and hopfully get a fix up as soon as possible. 

Background info incase anyone is interested: I moved the domain registration from nexusISP to ASW route 53.  Name servers for the domain were set, but the problem so far as I can see, is that I can't have a hosted site with neuxs without also buying a domain through them as well.  :disappointed:  This probably explains why it worked for a few days after the DNS move (the didn't detect the domain transfer, and probably only now  killed the associated server.)

The fix will probably entail rewriting the site in client only JS, and hosting that on S3 as well.  

I'll update this issue as I make progress.

**Comment by Diederikjh** [comment]
I have come up with a plan!
Just to keep everyone in the loop, the steps will be:

1. Add S3 hosting for domain, and put up a outage page.
2. Create a Lambda function to provide the fortune messages
3. Update page to GET the fortune string, and display it.
4. Put back the functional site.

I can't make any promises as to the timeline for when all this will happen, but  I'll update here as we progress.

**Comment by Diederikjh** [comment]
Step one complete! (I had to flush my DNS cache, but it seems to work)

**Comment by Diederikjh** [comment]
Seems like steps 3-4 are done now as well. Please let me know if any other issues arise!
Thanks again for reporting this.

**Comment by sm4rk0** [comment]
It's working flawlessly.
Thank you for maintaining this project!
